# Generated by Django 5.1.3 on 2025-01-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_l1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_l2',
        ),
    ]
